### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by egyshell** [jmpews/goscan#1]
i get this error , i'm don't have a good knowledge with go

panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x61b5e0, 0xc420012130)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
main.main()
	/home/mast3r/goscan/scanner.go:38 +0x1f0

**Comment by jmpews** [comment]
i update the code and readme.md. there is no exist target file before, and i add `wordpress.txt`, now you can try it. if you want to custom it , maybe you need to write some golang by yourself.
